### PR TITLE
Course -> CoursePage routing + connecting CoursePage with backend + some refactoring

### PR DESCRIPTION
**Pull request by illeanz**
Sorry for the confusion:

- made a new branch with just the needed changes and less code reformatting (hopefully easier to read)
- pulled in CI changes from master

### CODE REVIEW

**Review by aaronNgu — APPROVED** [review]

**Comment by wwyc** [comment]
The url for api and course page is the same right now.

For example when you refresh the page (http://localhost:9000/courses/CPSC340) it goes back to the api route.
Maybe use something slightly different?  maybe http://localhost:9000/coursepage/CPSC340?

**Comment by illeanz** [comment]
> The url for api and course page is the same right now.
> 
> For example when you refresh the page (http://localhost:9000/courses/CPSC340) it goes back to the api route.
> Maybe use something slightly different? maybe http://localhost:9000/coursepage/CPSC340?

omg youre right! Let me fix that real quick

**Review by aaronNgu — APPROVED** [review]
The bug seems to be fixed

**Review by wwyc — APPROVED** [review]

**Comment by wwyc** [comment]
code looks good but wasn't able to see deployment @aaronNgu 
since there is a routing change might want to double check it works in production
thanks!

**Comment by aaronNgu** [comment]
The fix 
Screen Shot 2020-07-30 at 10 01 01 AM

**Pull request merged**
