### PR TITLE
button and header components

### PR DESCRIPTION
**Pull request by Spandana-Baruah**

### CODE REVIEW

**Review by aaronNgu — COMMENTED** [review]
I think the "../index.css" isn't necessary since index.js has already import it for the whole application

**Comment by wwyc** [comment]
There are conflicts that need to be resolved first.

**Comment by Spandana-Baruah** [comment]
> There are conflicts that need to be resolved first.

Yup. I had made the PR before the CourseOverview PR was merged to master. The conflicts should be resolved now.

**Comment by Spandana-Baruah** [comment]
> I think the "../index.css" isn't necessary since index.js has already import it for the whole application

You're right! I've deleted the redundant css import statements

**Review by wwyc — APPROVED** [review]

**Pull request merged**
